### ISSUE TITLE
Set default timezone for new users from Adminpanel

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#224]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

There need to be way to set specific timezone for every new user.

### How to reproduce

...

**Comment by stefanpejcic** [comment]
This was requested and condidered, but since each user is on same mode, it should just inherit tu From master.

On user/plan level this can be pre-set in the docker file: https://github.com/stefanpejcic/OpenPanel/blob/f435338bda9970eb09fa19a154ae2d9bf819b4f4/docker/ubuntu_apache_mariadb/Dockerfile#L6
