### ISSUE TITLE
Package resources can't be updated

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#293]
### OpenPanel version(s) affected

0.3.7

### What OS are you using?

Ubuntu

### Description

Some resources of package can't be updated.
For example, when I change inode limit, it doesn't getting applied.
It needs to be checked if every package resources is applieed imeddiately..

### How to reproduce

...

**Comment by stefanpejcic** [comment]
You cannot increase the number of inodes on a file-based filesystem without also increasing its size because the number of inodes is directly tied to the filesystem's block size and the total storage space allocated during the storage file's creation - this is another downside of using docker at the current state without built-in disk size limits.

What we can do now is display a message stating that  inodes will not change without size increase, and do the actual change on disk increase - this has been on the todo list for a while, @p3t4rc did the actual plan-apply script - can you give it another try and do the inodes part?

![2024-12-05_16-41](https://github.com/user-attachments/assets/aa582d3b-9241-4712-ba13-b1ab45941eea)
